name: gcn
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.12
  - numpy=1.19.2
  - pytorch=1.6.0
  - torchvision=0.7.0
  - pip
  - pip:
    - nltk==3.5
    - sentence-transformers==0.4.1.2
    - sentencepiece==0.1.94
    - tokenizers==0.8.1rc2
    - torch-cluster==1.5.8
    - torch-geometric==1.4.3
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - tqdm==4.55.1
    - transformers==3.1.0
